export const modules = [
  {id:1,code:'01',title:'Fundamentos',sub:'La torre y su lenguaje',icon:'◎',color:'#a4ffdc',source:'https://docs.google.com/presentation/d/1zHc62ffayKJzVbFIfIyKgAnR6pGqkKuFY7L1-R7hRGo/edit'},
  {id:2,code:'02',title:'Instrumental',sub:'Reconocer antes de entregar',icon:'✦',color:'#ffd084',source:'https://docs.google.com/presentation/d/1Pxd3uMv7Uzyhw7e1sR_DWvunLcYxWiF_JUEnBTs-KvA/edit'},
  {id:3,code:'03',title:'Accesos',sub:'Geometría del campo',icon:'△',color:'#97c8ff',source:'https://docs.google.com/presentation/d/1_J-Vt_R81BILqhnX2w4hoFIw7x7fwBQbiDxvrcuG-wg/edit'},
  {id:4,code:'04',title:'Energía',sub:'Detectar antes de activar',icon:'ϟ',color:'#ff9e9e',source:'https://docs.google.com/presentation/d/1LX06MDcGdR03IK8UvWpLDYIiXbx4OJqE/edit'},
  {id:5,code:'05',title:'Campo',sub:'Señales en tiempo real',icon:'◈',color:'#a7adff',source:'https://docs.google.com/presentation/d/1uYUulC9oNThWxNjfp8_bEGcaQ9pRbbTe/edit'},
  {id:6,code:'06',title:'Sutura',sub:'Anticipar y conciliar',icon:'∞',color:'#ffaee0',source:'https://docs.google.com/presentation/d/16KYiT6SUtwrKuEKYJ5vu1cNYjJkmXCksFdXfrTrr-xw/edit'},
  {id:7,code:'07',title:'Especialidades',sub:'Preparar el set avanzado',icon:'✳',color:'#f7ea9b',source:'https://docs.google.com/presentation/d/1Oc2k1PaO1IBzwb3Z_oTyyddGpLSPx9tPOC0FA7t4iCQ/edit'},
];

export const missions = [
  {id:'1a',module:1,mode:'route',title:'La imagen tiene una ruta',brief:'Enlaza la cadena que lleva la señal de la cámara al monitor. Selecciona los nodos en orden.',lesson:'La cámara capta la imagen, el procesador la trata y el monitor la muestra. La fuente de luz pertenece a otra ruta.',nodes:[['cam','Cabezal de cámara'],['light','Fuente de luz'],['proc','Procesador de imagen'],['gas','Insuflador CO₂'],['mon','Monitor HD']],answer:['cam','proc','mon']},
  {id:'1b',module:1,mode:'route',title:'La luz antes de mirar',brief:'Traza la ruta de iluminación de la óptica; hay componentes de otras funciones mezclados.',lesson:'La fuente de luz se conecta mediante fibra óptica a la óptica laparoscópica.',nodes:[['fiber','Fibra óptica'],['optic','Óptica'],['camera','Procesador de cámara'],['source','Fuente de luz'],['insuff','Insuflador']],answer:['source','fiber','optic']},
  {id:'1c',module:1,mode:'route',title:'Circuito completo de vídeo',brief:'Ordena la ruta desde la escena iluminada hasta la imagen que interpreta el equipo.',lesson:'La óptica recoge la escena, el cabezal la convierte en señal, el procesador la trata y el monitor la presenta.',nodes:[['optic','Óptica laparoscópica'],['head','Cabezal de cámara'],['processor','Procesador de vídeo'],['monitor','Monitor'],['light','Fuente de luz'],['gas','Insuflador']],answer:['optic','head','processor','monitor']},
  {id:'1d',module:1,mode:'response',title:'La óptica mira en ángulo',brief:'Interpreta tres situaciones frecuentes con una óptica de 30°.',lesson:'Una óptica angulada cambia la dirección de visión al rotar; orientación, horizonte y objetivo deben comunicarse antes de manipular.',events:[
    {signal:'El objetivo sale del encuadre al rotar la óptica',choices:['Comunicar la rotación y recuperar la referencia visual','Aumentar la presión de CO₂','Cambiar el cable de energía'],correct:0},
    {signal:'El horizonte aparece inclinado',choices:['Continuar porque la imagen sigue encendida','Reorientar la cámara y confirmar el horizonte','Cambiar el trocar sin avisar'],correct:1},
    {signal:'La punta de un instrumento desaparece de la pantalla',choices:['Avanzar para encontrarla','Detener el movimiento y recuperar visión de la punta','Subir el brillo al máximo'],correct:1},
  ]},
  {id:'1e',module:1,mode:'order',title:'Antiempañamiento con trazabilidad',brief:'Ordena una respuesta de equipo ante una óptica empañada.',lesson:'La recuperación de visibilidad se realiza con comunicación, control del instrumento y verificación antes de reanudar.',cards:[['announce','Comunicar la pérdida de visibilidad'],['withdraw','Retirar o proteger la óptica según indique el equipo'],['clean','Limpiar y aplicar la medida antiempañamiento prevista'],['verify','Reconectar y confirmar imagen nítida']],answer:['announce','withdraw','clean','verify']},
  {id:'1f',module:1,mode:'fault',title:'Ergonomía antes de comenzar',brief:'Detecta tres condiciones del montaje que favorecen fatiga o movimientos inseguros.',lesson:'La ergonomía laparoscópica depende de una línea de visión cómoda, altura de trabajo adecuada y cables sin tensión ni cruces.',count:3,options:[['monitor','Monitor fuera de la línea de visión del operador'],['height','Altura de mesa que obliga a elevar los hombros'],['cables','Cables tensos cruzando la zona de movimiento'],['screen','Pantalla visible para el equipo'],['slack','Cables ordenados con holgura segura'],['stance','Espacio libre para una postura estable']],answer:['monitor','height','cables']},

  {id:'2a',module:2,mode:'pick',title:'Tres funciones, tres herramientas',brief:'Carga exactamente una pieza de visión, una de acceso y una de disección fina.',lesson:'Óptica, trocar y disector laparoscópico cubren funciones distintas; la elección debe responder a la solicitud del equipo.',count:3,options:[['optic','Óptica laparoscópica','VISIÓN'],['mary','Disector laparoscópico','DISECCIÓN'],['trocar','Trocar','ACCESO'],['babcock','Pinza Babcock laparoscópica','TRACCIÓN'],['needle','Portaagujas laparoscópico','SUTURA'],['gas','Insuflador','EQUIPO']],answer:['optic','mary','trocar']},
  {id:'2b',module:2,mode:'pick',title:'Preparación para tracción y sutura',brief:'La solicitud incluye tracción atraumática, sutura intracorpórea y visión. Elige tres piezas.',lesson:'La Babcock laparoscópica aporta tracción atraumática; el portaagujas laparoscópico permite manejar la aguja y la óptica da visión.',count:3,options:[['babcock','Pinza Babcock laparoscópica','TRACCIÓN'],['holder','Portaagujas laparoscópico','SUTURA'],['optic','Óptica 30°','VISIÓN'],['hook','Gancho monopolar','ENERGÍA'],['grasper','Grasper laparoscópico dentado','TRACCIÓN FIRME'],['tube','Tubo de CO₂','INSUFLACIÓN']],answer:['babcock','holder','optic']},
  {id:'2c',module:2,mode:'pick',title:'Tracción delicada bajo visión',brief:'El equipo solicita una pinza atraumática y visión. Selecciona exactamente dos elementos.',lesson:'La Babcock laparoscópica se destina a prensión atraumática; el grasper dentado corresponde a tracción firme y no es equivalente.',count:2,options:[['babcock','Pinza Babcock laparoscópica','TRACCIÓN ATRAUMÁTICA'],['optic','Óptica laparoscópica','VISIÓN'],['grasper','Grasper laparoscópico dentado','TRACCIÓN FIRME'],['hook','Gancho monopolar','ENERGÍA'],['trocar','Trocar','ACCESO']],answer:['babcock','optic']},
  {id:'2d',module:2,mode:'response',title:'Diámetro y puerto compatible',brief:'Responde a solicitudes donde instrumento, puerto y adaptador deben coincidir.',lesson:'Diámetro, longitud, sello y plataforma se confirman con el modelo real y el protocolo local antes de abrir o conectar.',events:[
    {signal:'El instrumento solicitado no pasa por el puerto disponible',choices:['Forzarlo con más presión','Detener y confirmar diámetro y alternativa compatible','Retirar el sello sin comunicar'],correct:1},
    {signal:'La etiqueta del envase no coincide con la solicitud',choices:['Abrirlo y comprobar después','Mantenerlo cerrado y aclarar la referencia','Usarlo si el mango se parece'],correct:1},
    {signal:'Se propone un adaptador no confirmado',choices:['Verificar compatibilidad e integridad antes de usar','Montarlo durante la activación','Ignorar el sello del puerto'],correct:0},
  ]},
  {id:'2e',module:2,mode:'fault',title:'Inspección de una pinza',brief:'Marca tres hallazgos que requieren retirar y verificar la pinza antes de entregarla.',lesson:'Mordazas, mecanismo, eje y aislamiento forman un conjunto; un defecto visible impide considerar el instrumento listo.',count:3,options:[['jaw','Mordazas desalineadas'],['ratchet','Mecanismo que no abre o bloquea correctamente'],['shaft','Daño visible en eje o aislamiento'],['label','Referencia coincidente con la solicitud'],['motion','Apertura y cierre uniformes'],['clean','Superficie íntegra y limpia']],answer:['jaw','ratchet','shaft']},
  {id:'2f',module:2,mode:'order',title:'Entrega con circuito cerrado',brief:'Ordena una entrega de instrumental con confirmación verbal.',lesson:'La comunicación de circuito cerrado reduce ambigüedades: solicitud, repetición, confirmación y entrega orientada.',cards:[['request','Escuchar la solicitud completa'],['repeat','Repetir nombre y característica crítica'],['confirm','Recibir confirmación del equipo'],['handoff','Entregar el instrumento orientado y visible']],answer:['request','repeat','confirm','handoff']},

  {id:'3a',module:3,mode:'tri',title:'Triángulo de trabajo',brief:'En este esquema didáctico, coloca la cámara en el vértice superior y separa los dos puertos de trabajo.',lesson:'La triangulación evita que los instrumentos queden paralelos y preserva una línea de visión útil. La ubicación real la decide el equipo según el procedimiento.',roles:[['camera','Cámara'],['left','Trabajo izquierdo'],['right','Trabajo derecho']],positions:[['top','Vértice superior'],['bottomLeft','Base izquierda'],['bottomRight','Base derecha']],answer:{top:'camera',bottomLeft:'left',bottomRight:'right'}},
  {id:'3b',module:3,mode:'tri',title:'Evita la espada de duelo',brief:'Ordena los roles en el esquema de cámara central y dos accesos laterales independientes.',lesson:'La separación de puertos ayuda a mantener instrumentos con trayectorias distintas. Es una simplificación visual, no una guía de colocación clínica.',roles:[['left','Instrumento A'],['camera','Cámara'],['right','Instrumento B']],positions:[['top','Línea de visión'],['bottomLeft','Acceso lateral A'],['bottomRight','Acceso lateral B']],answer:{top:'camera',bottomLeft:'left',bottomRight:'right'}},
  {id:'3c',module:3,mode:'response',title:'El efecto fulcro',brief:'Interpreta cómo cambia el movimiento al pivotar en un puerto.',lesson:'El puerto funciona como punto de apoyo: un desplazamiento externo puede producir movimiento interno opuesto. Se entrena con supervisión y visión continua.',events:[
    {signal:'El mango se desplaza hacia la izquierda',choices:['La punta tiende a moverse hacia la derecha','La punta siempre se mueve a la izquierda','La punta no cambia de posición'],correct:0},
    {signal:'La punta se acerca a una estructura fuera del objetivo',choices:['Acelerar para superar el punto','Detener, recuperar referencia y corregir con movimientos pequeños','Rotar el monitor'],correct:1},
    {signal:'Un movimiento externo mínimo produce gran desplazamiento en pantalla',choices:['Mantener movimientos deliberados y confirmar profundidad','Aumentar el movimiento del mango','Ignorar la escala de la imagen'],correct:0},
  ]},
  {id:'3d',module:3,mode:'response',title:'Horizonte estable',brief:'Responde a cambios de orientación producidos por cámara y puertos.',lesson:'La orientación estable requiere referencias compartidas; una cámara lateral o rotada puede alterar la interpretación de arriba, abajo, izquierda y derecha.',events:[
    {signal:'La cámara entra por un puerto lateral',choices:['Acordar la nueva orientación antes de continuar','Asumir que la vista será idéntica','Cambiar instrumentos sin mirar'],correct:0},
    {signal:'La imagen rota durante una maniobra',choices:['Detener y restablecer el horizonte','Compensar moviendo ambas pinzas a ciegas','Aumentar la insuflación'],correct:0},
    {signal:'El operador y el asistente usan referencias distintas',choices:['Continuar hasta que coincidan','Nombrar una referencia común y confirmarla','Apagar la pantalla secundaria'],correct:1},
  ]},
  {id:'3e',module:3,mode:'tri',title:'Tres trayectorias sin colisión',brief:'Asigna visión central y dos trayectorias de trabajo separadas.',lesson:'La cámara debe conservar la línea de visión mientras los dos instrumentos mantienen trayectorias externas diferenciadas; el esquema no prescribe sitios anatómicos.',roles:[['left','Instrumento de exposición'],['camera','Cámara'],['right','Instrumento de trabajo']],positions:[['top','Línea de visión'],['bottomLeft','Trayectoria lateral A'],['bottomRight','Trayectoria lateral B']],answer:{top:'camera',bottomLeft:'left',bottomRight:'right'}},
  {id:'3f',module:3,mode:'order',title:'Pausa antes del acceso',brief:'Ordena una verificación de equipo previa al acceso laparoscópico.',lesson:'La técnica y el sitio de acceso los decide el equipo responsable; el personal confirma material, antecedentes comunicados, disponibilidad y pausa antes de proceder.',cards:[['brief','Confirmar plan y factores de riesgo comunicados'],['equipment','Verificar acceso solicitado, calibre e integridad'],['team','Realizar la pausa y confirmar preparación del equipo'],['proceed','Continuar solo con autorización del responsable']],answer:['brief','equipment','team','proceed']},
  {id:'3g',module:3,mode:'fault',title:'Espacio restringido',brief:'Detecta tres señales de geometría deficiente que deben comunicarse.',lesson:'Paralelismo, palancas extremas y puntas fuera de visión reducen control y aumentan colisiones; la corrección corresponde al equipo bajo visión.',count:3,options:[['parallel','Instrumentos casi paralelos sin separación de trabajo'],['lever','Mangos forzados al límite contra los puertos'],['tips','Puntas activas fuera del campo visual'],['horizon','Horizonte estable'],['separate','Trayectorias externas diferenciadas'],['visible','Puntas visibles antes de mover']],answer:['parallel','lever','tips']},

  {id:'4a',module:4,mode:'fault',title:'Inspección de energía',brief:'Marca las tres señales que obligan a detener y verificar antes de usar energía.',lesson:'El aislamiento, el retorno y la activación bajo visión son controles de seguridad descritos en el módulo.',count:3,options:[['insul','Aislamiento del electrodo con grieta'],['return','Placa de retorno sin verificación'],['blind','Activación propuesta fuera de la visión'],['label','Cable identificado y compatible'],['mode','Modo anunciado al equipo'],['stand','Dispositivo en soporte aislante']],answer:['insul','return','blind']},
  {id:'4b',module:4,mode:'fault',title:'Sistema combinado: alerta',brief:'Encuentra tres condiciones que requieren aclaración antes de conectar el dispositivo.',lesson:'La compatibilidad del generador, la integridad física y la comunicación del modo deben confirmarse antes del uso.',count:3,options:[['mismatch','Generador de otra plataforma sin compatibilidad confirmada'],['damage','Cable con daño visible'],['unknown','Modo de energía no comunicado'],['checked','Conector íntegro'],['team','Responsable presente para prueba'],['rest','Punta en soporte aislante']],answer:['mismatch','damage','unknown']},
  {id:'4c',module:4,mode:'response',title:'Calor residual',brief:'Reconoce que la desactivación no garantiza una punta fría.',lesson:'Algunos dispositivos conservan calor después de activarse; se mantienen visibles, separados de tejidos y en el soporte previsto hasta que el equipo confirme seguridad.',events:[
    {signal:'El dispositivo acaba de desactivarse',choices:['Asumir que está frío','Mantener la punta visible y alejada hasta confirmar','Apoyarlo sobre el campo'],correct:1},
    {signal:'Se solicita cambiar de instrumento inmediatamente',choices:['Comunicar que la punta puede conservar calor y usar el soporte','Entregarlo cruzando cables','Enfriarlo con cualquier líquido'],correct:0},
    {signal:'La punta toca otro instrumento tras activarse',choices:['Ignorarlo porque ya está apagado','Avisar y verificar posible transferencia térmica','Subir el modo de energía'],correct:1},
  ]},
  {id:'4d',module:4,mode:'fault',title:'Acoplamiento directo',brief:'Marca tres situaciones que pueden transferir energía a un elemento no previsto.',lesson:'El acoplamiento directo puede ocurrir cuando un electrodo activo contacta otro instrumento conductor; visión, separación y comunicación son barreras.',count:3,options:[['touch','Electrodo activo en contacto con otra pinza metálica'],['hidden','Activación con el punto de contacto fuera de visión'],['crowded','Instrumentos conductores amontonados alrededor de la punta'],['separate','Punta separada y visible'],['announce','Activación anunciada'],['holder','Dispositivo inactivo en soporte aislante']],answer:['touch','hidden','crowded']},
  {id:'4e',module:4,mode:'fault',title:'Corriente fuera de vista',brief:'Selecciona tres riesgos que pueden causar una lesión lejos de la punta observada.',lesson:'Fallo de aislamiento, acoplamiento capacitivo y activación fuera de visión son mecanismos de energía no deseada descritos por FUSE.',count:3,options:[['crack','Defecto de aislamiento en el eje'],['capacitive','Electrodo activo paralelo a una cánula conductora sin verificación'],['blind','Activación con parte del instrumento fuera de visión'],['intact','Aislamiento inspeccionado e íntegro'],['lowest','Configuración confirmada por el responsable'],['visible','Punta completamente visible']],answer:['crack','capacitive','blind']},
  {id:'4f',module:4,mode:'order',title:'Plataforma correcta',brief:'Ordena la preparación de un dispositivo de energía antes de su prueba.',lesson:'La preparación segura comienza con identificación y compatibilidad, continúa con inspección y configuración comunicada y termina con una prueba controlada.',cards:[['identify','Identificar dispositivo, cable y generador solicitados'],['compatibility','Confirmar compatibilidad e integridad'],['settings','Comunicar y confirmar el modo previsto'],['test','Realizar la prueba indicada por el fabricante y el protocolo']],answer:['identify','compatibility','settings','test']},
  {id:'4g',module:4,mode:'response',title:'Humo y cable de luz',brief:'Distingue dos riesgos que pueden persistir fuera del punto de activación.',lesson:'El humo reduce visibilidad y el extremo del cable de luz puede actuar como fuente térmica; ambos requieren comunicación y manejo conforme al equipo y protocolo.',events:[
    {signal:'El humo oculta la punta activa',choices:['Continuar por memoria','Detener activación y recuperar visibilidad','Aumentar el zoom'],correct:1},
    {signal:'El cable de luz queda desconectado pero encendido',choices:['Colocarlo sobre el campo','Apagarlo o asegurarlo según protocolo y comunicar','Cubrirlo con una compresa'],correct:1},
    {signal:'La visibilidad mejora solo de forma intermitente',choices:['Revisar evacuación, lente y fuente con el equipo','Aumentar energía','Ignorar la alarma del insuflador'],correct:0},
  ]},

  {id:'5a',module:5,mode:'response',title:'Sala de señales',brief:'Responde a cada aviso del campo. La prioridad es comunicar y verificar, no improvisar.',lesson:'Imagen, luz y presión son sistemas distintos; un cambio de señal necesita una comprobación dirigida con el equipo.',events:[
    {signal:'Imagen borrosa',choices:['Limpiar y verificar la óptica con el equipo','Aumentar la presión de CO₂','Ignorarla mientras se vea algo'],correct:0},
    {signal:'Campo oscuro',choices:['Cambiar el trocar sin avisar','Revisar fuente de luz y fibra óptica','Seguir sin iluminación'],correct:1},
    {signal:'Presión cae súbitamente',choices:['Comprobar conexiones y válvulas; comunicar','Subir la energía monopolar','Apagar el monitor'],correct:0},
  ]},
  {id:'5b',module:5,mode:'response',title:'Control de visibilidad',brief:'Tres alertas nuevas; identifica el sistema que corresponde antes de continuar.',lesson:'Balance de blancos, señal de cámara y neumoperitoneo se revisan por rutas diferentes.',events:[
    {signal:'Color de imagen incorrecto',choices:['Repetir balance de blancos','Cerrar la válvula del trocar','Cambiar el portaagujas'],correct:0},
    {signal:'Monitor encendido, sin imagen',choices:['Abrir más CO₂','Revisar entrada y conexión procesador-monitor','Activar el dispositivo de energía'],correct:1},
    {signal:'Alarma del insuflador',choices:['Silenciar sin comprobar','Informar y revisar el sistema de gas','Aumentar brillo de pantalla'],correct:1},
  ]},
  {id:'5c',module:5,mode:'response',title:'La presión habla',brief:'Clasifica alertas del neumoperitoneo antes de responder.',lesson:'Una alarma puede asociarse a fuga, obstrucción, desconexión o límite de presión; no se silencia sin identificar el sistema y comunicar.',events:[
    {signal:'La presión cae y el flujo aumenta',choices:['Buscar una posible fuga o puerto abierto con el equipo','Subir energía monopolar','Desconectar el monitor'],correct:0},
    {signal:'La presión sube y el flujo se detiene',choices:['Revisar obstrucción o condición del sistema y avisar','Abrir todos los puertos','Ignorar el valor'],correct:0},
    {signal:'No llega gas después de cambiar el cilindro o fuente',choices:['Comprobar conexión, válvulas y selección de fuente','Cambiar la óptica','Activar succión sin comunicar'],correct:0},
  ]},
  {id:'5d',module:5,mode:'response',title:'Humo, vaho o sangre',brief:'Diferencia causas de pérdida de imagen antes de actuar.',lesson:'La apariencia de la imagen orienta la comprobación, pero el equipo confirma la causa; no se manipula a ciegas.',events:[
    {signal:'Halo lechoso uniforme tras introducir la óptica',choices:['Considerar vaho o suciedad y verificar la lente','Asumir sangrado','Aumentar potencia de luz sin límite'],correct:0},
    {signal:'Nube que aparece durante activación de energía',choices:['Considerar humo y recuperar evacuación/visibilidad','Cambiar el portaagujas','Cerrar todos los puertos'],correct:0},
    {signal:'Cambio rojo súbito que oculta referencias',choices:['Comunicar de inmediato y mantener visión para la respuesta del equipo','Limpiar pantalla externa','Continuar el movimiento'],correct:0},
  ]},
  {id:'5e',module:5,mode:'order',title:'Comunicación en circuito cerrado',brief:'Ordena una comunicación ante una alerta de equipo.',lesson:'Un mensaje cerrado incluye aviso claro, repetición del receptor, confirmación y reporte del resultado.',cards:[['call','Emitir un aviso específico y nombrar el sistema'],['repeat','El receptor repite la instrucción'],['confirm','Quien la emitió confirma o corrige'],['report','El receptor informa el resultado']],answer:['call','repeat','confirm','report']},
  {id:'5f',module:5,mode:'order',title:'Cambio súbito del campo',brief:'Ordena prioridades de equipo ante una pérdida inesperada de visibilidad.',lesson:'La respuesta del personal se centra en avisar, conservar la visión disponible, preparar lo solicitado y documentar la conciliación; las decisiones clínicas corresponden al responsable.',cards:[['announce','Comunicar el cambio de inmediato'],['vision','Mantener o recuperar una vista útil sin movimientos ciegos'],['prepare','Preparar el material solicitado por el responsable'],['reconcile','Confirmar lo usado y el estado del campo antes de avanzar']],answer:['announce','vision','prepare','reconcile']},

  {id:'6a',module:6,mode:'order',title:'Antes de entregar la aguja',brief:'Ordena el flujo de preparación del instrumentista para el tiempo de sutura.',lesson:'La preparación combina confirmación del material, inspección del conjunto y conteo compartido antes de entregar.',cards:[['confirm','Confirmar material y calibre solicitados'],['inspect','Inspeccionar aguja y portaagujas'],['count','Establecer el conteo con circulante'],['handoff','Entregar al equipo el conjunto verificado']],answer:['confirm','inspect','count','handoff']},
  {id:'6b',module:6,mode:'order',title:'Cierre del tiempo de sutura',brief:'Reconstruye el control del material al terminar este tiempo.',lesson:'La trazabilidad de aguja e instrumentos se confirma con el equipo antes de cerrar la entrega.',cards:[['announce','Recibir aviso de fin del tiempo de sutura'],['retrieve','Recuperar aguja e instrumental usados'],['recount','Conciliar el conteo con circulante'],['report','Comunicar cualquier discrepancia antes de avanzar']],answer:['announce','retrieve','recount','report']},
  {id:'6c',module:6,mode:'order',title:'Orientación de la aguja',brief:'Ordena la preparación cognitiva antes de entregar una aguja cargada.',lesson:'La carga exacta depende de la solicitud del operador; el flujo seguro confirma material, inspecciona, orienta según la indicación y verifica antes de transferir.',cards:[['material','Confirmar sutura, aguja y solicitud'],['inspect','Inspeccionar integridad de aguja y portaagujas'],['orient','Cargar y orientar según la indicación recibida'],['verify','Mostrar y confirmar antes de entregar']],answer:['material','inspect','orient','verify']},
  {id:'6d',module:6,mode:'tri',title:'Dos manos, dos funciones',brief:'Asigna visión, exposición y conducción de aguja en un esquema de coordinación bimanual.',lesson:'La mano no dominante suele mantener exposición mientras la dominante conduce la aguja y la cámara conserva visión; es un modelo didáctico, no una prescripción técnica.',roles:[['expose','Exposición estable'],['needle','Conducción de aguja'],['camera','Visión']],positions:[['top','Visión estable'],['bottomLeft','Mano no dominante'],['bottomRight','Mano dominante']],answer:{top:'camera',bottomLeft:'expose',bottomRight:'needle'}},
  {id:'6e',module:6,mode:'response',title:'Tensión sin exceso',brief:'Reconoce señales de tensión inadecuada durante una tarea simulada de sutura.',lesson:'La tensión se valora con el equipo: demasiada puede comprometer tejido y muy poca puede dejar el cierre inestable; la pantalla no sustituye la supervisión ni la evaluación clínica.',events:[
    {signal:'El tejido se deforma marcadamente al ajustar',choices:['Comunicar posible exceso de tensión','Apretar más','Cambiar la cámara'],correct:0},
    {signal:'El lazo pierde aproximación al soltar',choices:['Comunicar posible tensión insuficiente y verificar','Ignorarlo','Aumentar la insuflación'],correct:0},
    {signal:'La línea de sutura sale del campo',choices:['Detener y recuperar visión antes de continuar','Seguir por memoria','Mover ambos instrumentos rápido'],correct:0},
  ]},
  {id:'6f',module:6,mode:'order',title:'Aguja no localizada',brief:'Ordena la respuesta de trazabilidad ante una aguja que no se ve.',lesson:'Una discrepancia requiere alto, comunicación y conciliación sistemática según protocolo; el juego no sustituye el procedimiento institucional de búsqueda.',cards:[['stop','Detener la progresión y mantener el campo controlado'],['announce','Comunicar que la aguja no está localizada'],['reconcile','Conciliar conteo, portaagujas y zonas de transferencia'],['protocol','Seguir la búsqueda y escalamiento del protocolo institucional']],answer:['stop','announce','reconcile','protocol']},

  {id:'7a',module:7,mode:'loadout',title:'Set avanzado: bariátrica',brief:'El equipo solicita exposición hepática, grapado y extracción protegida. Asigna un elemento a cada función.',lesson:'En el material del módulo se describen retractor hepático, grapadora y bolsa de extracción como componentes del set bariátrico; confirma siempre la solicitud local.',slots:[['expose','Exposición'],['divide','Grapado'],['extract','Extracción']],items:[['nathanson','Retractor Nathanson'],['stapler','Grapadora Endo-GIA'],['bag','Bolsa de extracción'],['maryland','Disector laparoscópico']],answer:{expose:'nathanson',divide:'stapler',extract:'bag'}},
  {id:'7b',module:7,mode:'loadout',title:'Set avanzado: colorrectal',brief:'Se solicita visión, anastomosis circular y extracción contenida. Relaciona cada función.',lesson:'La preparación por especialidad exige confirmar el procedimiento y la compatibilidad de cada dispositivo con el equipo.',slots:[['vision','Visión'],['join','Anastomosis'],['extract','Extracción']],items:[['optic','Óptica laparoscópica'],['circular','Grapadora circular EEA'],['bag','Bolsa de extracción'],['hook','Gancho monopolar']],answer:{vision:'optic',join:'circular',extract:'bag'}},
  {id:'7c',module:7,mode:'order',title:'Pausa de seguridad biliar',brief:'Ordena un punto de control del equipo antes de dividir estructuras en una simulación.',lesson:'La guía multisocietaria recomienda la visión crítica de seguridad para identificación anatómica. El instrumentista apoya la pausa y la comunicación; la decisión clínica corresponde al cirujano.',cards:[['expose','Confirmar exposición y visibilidad suficientes'],['identify','Solicitar o escuchar la identificación anatómica explícita'],['team','Confirmar que el equipo comparte el punto de control'],['authorize','Continuar únicamente con la indicación del responsable']],answer:['expose','identify','team','authorize']},
  {id:'7d',module:7,mode:'response',title:'Anastomosis colorrectal: preparación',brief:'Resuelve tres comprobaciones de instrumental sin ejecutar la técnica.',lesson:'La preparación de una grapadora circular exige confirmar referencia, componentes, compatibilidad y trazabilidad conforme al fabricante y al protocolo local.',events:[
    {signal:'El tamaño solicitado no coincide con el envase',choices:['Mantener cerrado y aclarar la referencia','Abrirlo para comparar','Elegir por color del mango'],correct:0},
    {signal:'Falta un componente del sistema solicitado',choices:['Continuar con una pieza parecida','Detener la preparación y comunicar la discrepancia','Sustituirlo sin informar'],correct:1},
    {signal:'La verificación final aún no se ha comunicado',choices:['Entregar el dispositivo','Completar la confirmación de componentes y trazabilidad','Retirar la óptica'],correct:1},
  ]},
  {id:'7e',module:7,mode:'fault',title:'Grapado bariátrico: alerta',brief:'Marca tres condiciones que impiden considerar la grapadora lista.',lesson:'Cartucho, plataforma, integridad y referencia se confirman antes de entregar. El juego no enseña selección clínica de carga ni técnica de grapado.',count:3,options:[['cartridge','Cartucho o carga no confirmados'],['platform','Compatibilidad con la plataforma en duda'],['inspect','Dispositivo sin inspección de integridad'],['matched','Referencia coincidente con la solicitud'],['closed','Envase íntegro hasta la confirmación'],['team','Solicitud repetida y confirmada']],answer:['cartridge','platform','inspect']},
  {id:'7f',module:7,mode:'loadout',title:'Set ginecológico laparoscópico',brief:'Asocia visión, manipulación y sutura en un set genérico.',lesson:'Los procedimientos ginecológicos varían; esta actividad solo relaciona funciones básicas y exige confirmar la solicitud específica del equipo.',slots:[['vision','Visión'],['handle','Manipulación'],['suture','Sutura']],items:[['optic','Óptica laparoscópica'],['grasper','Grasper laparoscópico dentado'],['holder','Portaagujas laparoscópico'],['gas','Insuflador']],answer:{vision:'optic',handle:'grasper',suture:'holder'}},
];
