// Fotografías de Wikimedia Commons y de una publicación CC BY. Véase CREDITOS-IMAGENES.md.
export const visualAtlas={
  1:[
    {file:'theatre',title:'Quirófano laparoscópico',kind:'FOTOGRAFÍA REAL',caption:'Reconoce el entorno y localiza la torre con pantallas y equipos antes de trazar la cadena de imagen.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg',points:[{x:34,y:53,label:'Torre audiovisual',note:'La torre con pantallas se aprecia a la izquierda de la mesa. La ruta de imagen se resuelve por componentes, no por la posición física en la foto.'},{x:48,y:65,label:'Mesa de operaciones',note:'La mesa es un elemento del entorno, no un nodo de la cadena de vídeo.'}]},
    {file:'lap-tower',title:'Torre de laparoscopia',kind:'FOTOGRAFÍA REAL',caption:'Torre STORZ fotografiada durante una donación hospitalaria. El monitor y una unidad de equipo son visibles detrás de las personas; no se deben inferir conexiones desde esta imagen.',credit:'Justin Ontiveros / U.S. Navy · dominio público',source:'https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Laparoscopy_donation_(8147071).jpg'},
    {file:'instruments',title:'Instrumental laparoscópico',kind:'FOTOGRAFÍA REAL',caption:'Observa el eje largo y los mandos de instrumentos reales. Su forma no identifica por sí sola la ruta de señal.',credit:'ignis · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_Hand_Instruments_001_JPN.jpg'},
    {file:'camara-laparoscopica',title:'Cabezal de cámara',kind:'FOTOGRAFÍA REAL',caption:'Cabezal de cámara con su cable hacia el procesador. Es el nodo «cam» / «head» de la ruta de vídeo: capta la imagen que llega desde la óptica.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:72,y:55,label:'Acople a la óptica',note:'Aquí se conecta el cabezal a la óptica laparoscópica; de ese acople sale la imagen que el cabezal convierte en señal.'},{x:22,y:45,label:'Cable al procesador',note:'El cable lleva la señal de vídeo hasta el procesador; no confundir con el cable de fibra, que lleva luz.'}]},
    {file:'procesador',title:'Procesador de vídeo (hub)',kind:'FOTOGRAFÍA REAL',caption:'Procesador con el cabezal de cámara conectado. Recibe la señal del cabezal, la trata y la envía al monitor: es el nodo «proc» / «processor».',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:78,y:38,label:'Conector del cabezal',note:'El cabezal de cámara se conecta aquí; un conector suelto o mal ajustado deja el monitor sin señal.'},{x:22,y:75,label:'Panel frontal',note:'El procesador identifica el equipo y su compatibilidad; no se sustituye por uno de otra plataforma sin confirmarlo.'}]},
    {file:'fuente-luz',title:'Fuente de luz',kind:'FOTOGRAFÍA REAL',caption:'Fuente de luz encendida, con el cable de fibra conectado. Es el nodo «light» / «source»: sin ella, la óptica no tiene luz que llevar al campo.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:20,y:65,label:'Salida de fibra',note:'El cable de fibra óptica se conecta aquí; por esta salida sale la luz hacia la óptica.'}]},
    {file:'cable-fibra',title:'Cable de fibra óptica',kind:'FOTOGRAFÍA REAL',caption:'Cable de fibra óptica con sus dos conectores. Lleva la luz desde la fuente hasta la óptica; no lleva señal de vídeo ni de gas.',credit:'GPA Academy · Fotografía propia',source:''},
    {file:'optica-30',title:'Óptica de 30°',kind:'FOTOGRAFÍA REAL',caption:'Óptica de 30° real. El poste azul orienta la dirección de visión; rotarlo cambia hacia dónde mira el ángulo, como en el desafío «La óptica mira en ángulo».',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:18,y:26,label:'Poste de luz',note:'El poste indica la dirección del bisel; rotarlo cambia hacia dónde mira la óptica de 30°.'},{x:88,y:78,label:'Bisel de la punta',note:'El corte angulado de la punta define el ángulo de visión: 30° aquí, recto en una óptica de 0°.'}]},
    {file:'optica-0-diagrama',title:'Ángulo de visión: 0°',kind:'ESQUEMA · NO FOTOGRAFÍA',caption:'Diagrama propio que ilustra el ángulo de visión de una óptica de 0°: mira en línea recta con el eje, a diferencia de la de 30° de la imagen anterior.',credit:'GPA Academy · Diseño propio',source:''},
    {file:'torre-completa',title:'Torre laparoscópica completa',kind:'FOTOGRAFÍA REAL',caption:'Carro de la torre con sus equipos apilados. La disposición exacta de cada equipo varía según el fabricante y el protocolo local; no la memorices como única distribución posible.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:42,y:14,label:'Monitor',note:'Muestra la imagen que llega del procesador de vídeo.'},{x:38,y:46,label:'Sistema de vídeo',note:'Cabezal y procesador de la cadena de imagen, apilados en los estantes superiores.'},{x:38,y:60,label:'Generador electroquirúrgico',note:'Unidad de energía; sus mandos y pantallas suelen ir en un módulo propio, separado del sistema de vídeo.'},{x:38,y:69,label:'Insuflador',note:'Controla presión y flujo de CO₂; suele reconocerse por sus mandos redondos.'}]}
  ,
    {file:'pedal',title:'Pedal de activación',kind:'FOTOGRAFÍA REAL',caption:'Pedal de dos pistones (corte/coag) con su cable al generador. Su ubicación respecto al operador es justo lo que se evalúa en el desafío de ergonomía.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:40,y:72,label:'Pistón (por ejemplo, ablate)',note:'Cada pistón activa un modo distinto; se confirma cuál es cuál antes de empezar.'},{x:75,y:55,label:'Pistón (por ejemplo, coag)',note:'Dos pistones separados evitan activar el modo equivocado por error.'},{x:28,y:40,label:'Conector al generador',note:'El cable se revisa e identifica junto con el generador antes de la prueba.'}]},
    {file:'cable-luz-2',title:'Cable de fibra óptica (otro modelo)',kind:'FOTOGRAFÍA REAL',caption:'Otro cable de fibra óptica real, con conectores distintos al de la imagen anterior. Sigue siendo luz, no señal de vídeo ni energía: los conectores varían según el fabricante, pero la función es la misma.',credit:'GPA Academy · Fotografía propia',source:''}],
  2:[
    {file:'hernia-set',title:'Mesa de instrumental',kind:'FOTOGRAFÍA REAL',caption:'Un set real mezcla acceso, manipulación, cables y otros elementos. Inspecciona las zonas numeradas y confirma el modelo solicitado.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg',points:[{x:15,y:34,label:'Instrumentos de acceso',note:'La zona izquierda contiene instrumentos de acceso. En un caso real se confirman tipo y calibre antes de seleccionarlos.'},{x:53,y:34,label:'Pinzas largas',note:'En el centro hay instrumentos largos de manipulación. La foto no basta para identificar cada modelo específico.'},{x:81,y:22,label:'Cable y conexión',note:'Los cables se inspeccionan y se relacionan con el equipo compatible; no se eligen por apariencia solamente.'}]},
    {file:'dissector',title:'Disector laparoscópico',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Mango, eje largo y mordazas de un disector laparoscópico. La fuente no especifica el subtipo Maryland, por lo que el juego no le atribuye ese nombre.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_disektor.jpg'},
    {file:'grasper',title:'Grasper laparoscópico dentado',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Mango, eje largo y mordazas dentadas de un grasper laparoscópico. Es una pinza laparoscópica de tracción firme, no una Babcock.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_grasp.jpg'},
    {file:'trocar-product',title:'Familia de trocares',kind:'FOTOGRAFÍA REAL',caption:'Fotografía de trocares desechables. El modelo y calibre se confirman en el material solicitado; la foto no identifica el producto del desafío.',credit:'Magnus1313 · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Trocar_family.jpg'},
    {file:'babcock-laparoscopic',title:'Babcock laparoscópica de 5 mm',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Detalle distal aislado de una Babcock laparoscópica reutilizable de 5 mm, con mordazas redondeadas y fenestradas para prensión atraumática.',credit:'Bezerra et al. · Figura 1A recortada · CC BY 4.0',source:'https://periodicos.newsciencepubl.com/arace/article/view/8981'}
  ,
    {file:'mesa-instrumental-2',title:'Mesa de instrumental preparada',kind:'FOTOGRAFÍA REAL',caption:'Otra mesa real, con el instrumental laparoscópico ordenado antes del procedimiento. Compara con la mesa de hernia: el orden y la disposición cambian según el equipo y el caso, no hay una única forma correcta.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:45,y:48,label:'Instrumental ordenado',note:'Cada pieza se coloca de forma visible y accesible antes de comenzar; el orden exacto lo define el equipo.'}]},
    {file:'maryland-real',title:'Disector Maryland',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Disector identificado por GPA Academy como Maryland: mordazas curvas y finas, más delicadas que las de un grasper dentado. A diferencia del disector genérico de Wikimedia usado en otras tarjetas, aquí el subtipo lo confirma directamente quien fotografió su propio instrumento.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:20,y:28,label:'Mordazas curvas',note:'El perfil curvo y fino es característico del Maryland; permite disecar con precisión sin desgarrar tejido.'},{x:68,y:75,label:'Anillos del mango',note:'El mango de anillas facilita el control fino de la apertura durante la disección.'}]},
    {file:'trocares-tamanos',title:'Trocares de varios calibres',kind:'FOTOGRAFÍA REAL',caption:'Cuatro trocares del mismo sistema, en calibres crecientes (5, 10, 12 y 15). El calibre solicitado debe confirmarse antes de abrir: un instrumento de mayor diámetro no pasa por un puerto más pequeño.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:10,y:55,label:'Calibre menor',note:'El más delgado de la serie; suele reservarse para óptica o instrumentos finos.'},{x:90,y:45,label:'Calibre mayor',note:'El más ancho de la serie; por aquí pasan instrumentos de mayor diámetro, como grapadoras.'}]},
    {file:'mesa-instrumental-3',title:'Mesa con cables e instrumental',kind:'FOTOGRAFÍA REAL',caption:'Una tercera mesa real, con instrumental y cables de distintos colores. Cada cable se identifica y se relaciona con su equipo compatible antes de conectarlo, como en el desafío de diámetro y puerto compatible.',credit:'GPA Academy · Fotografía propia',source:''}],
  3:[
    {file:'access',title:'Acceso con puerto real',kind:'FOTOGRAFÍA CLÍNICA',caption:'Imagen clínica de un acceso transumbilical. El esquema del desafío simplifica la triangulación; no prescribe sitios de inserción.',credit:'G Srikanth et al. · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopy_01.jpg',points:[{x:59,y:46,label:'Puerto de acceso',note:'Aquí se ve el puerto de acceso. La foto documenta un procedimiento específico; no define por sí sola la geometría de otros casos.'}]},
    {file:'position',title:'Posición de Trendelenburg',kind:'FOTOGRAFÍA CON MANIQUÍ',caption:'La fotografía ilustra la inclinación cefálica inferior. La posición real depende del procedimiento y del equipo.',credit:'G. Rees Doyle y J. A. McCutcheon · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Trendelenburg_position.jpg',points:[{x:13,y:43,label:'Extremo cefálico',note:'La cabeza del maniquí queda más baja que los pies en esta demostración de Trendelenburg.'},{x:88,y:29,label:'Extremo podálico',note:'El extremo de los pies queda elevado. El equipo establece la posición y protege al paciente según el procedimiento.'}]},
    {file:'trocar',title:'Esquema de puertos',kind:'ESQUEMA · NO FOTOGRAFÍA',caption:'Distribución ilustrativa de accesos. No usar como plantilla de colocación clínica.',credit:'Huatulco · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Trocar_in_VLC.JPG'}
  ,
    {file:'valvula-trocar',title:'Válvula de un trocar',kind:'FOTOGRAFÍA REAL',caption:'Detalle de la válvula y el sello de un trocar real. Un sello íntegro mantiene el neumoperitoneo; una válvula que no cierra bien es una causa típica de fuga, como en el desafío de presión.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:35,y:55,label:'Sello de la válvula',note:'Un sello dañado o mal cerrado deja escapar CO₂: es una causa frecuente de fuga.'},{x:15,y:65,label:'Llave lateral',note:'Una llave abierta por descuido también produce una fuga de gas.'}]}],
  4:[{file:'dissector',title:'Disector laparoscópico bajo inspección',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Examina mango, eje y extremo de este disector laparoscópico. Los fallos descritos en la misión son un escenario simulado, no defectos visibles en esta foto.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_disektor.jpg',points:[{x:21,y:51,label:'Mango',note:'Comprueba integridad y mecanismo del mango según la lista de verificación local.'},{x:58,y:23,label:'Eje laparoscópico',note:'Inspecciona el eje y su aislamiento cuando el dispositivo utiliza energía. La foto no representa un daño real.'},{x:90,y:34,label:'Extremo de trabajo',note:'Confirma la integridad del extremo y la compatibilidad antes del uso.'}]},
    {file:'generador',title:'Generador electroquirúrgico',kind:'FOTOGRAFÍA REAL',caption:'Generador con bipolar conectada (sin placa de retorno) y monopolar conectada (con placa de retorno). Los modos CUT, COAG y BIPOLAR se programan y comunican por separado.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:85,y:34,label:'Zócalo de la placa de retorno',note:'Aquí se conecta la placa de retorno de la monopolar; la bipolar no usa este zócalo.'},{x:87,y:52,label:'Salida bipolar',note:'La bipolar conduce la corriente entre sus propias mordazas, sin placa de retorno.'},{x:50,y:27,label:'Pantallas de modo',note:'CUT, COAG y BIPOLAR se configuran y comunican al equipo antes de activar.'}]},
    {file:'pinza-bipolar',title:'Pinza bipolar laparoscópica',kind:'FOTOGRAFÍA REAL',caption:'Pinza bipolar de mordazas fenestradas, con su propio cable. La corriente circula entre las dos mordazas: por eso la bipolar no necesita placa de retorno, a diferencia del gancho monopolar.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:6,y:33,label:'Mordazas',note:'La corriente circula entre estas dos mordazas; no requiere placa de retorno.'},{x:33,y:80,label:'Conector bipolar',note:'Este conector de dos clavijas es característico de la bipolar; el monopolar usa un solo conector y necesita placa de retorno.'}]},
    {file:'placa-retorno',title:'Placa de retorno monopolar',kind:'FOTOGRAFÍA REAL',caption:'Placa de retorno (electrodo dispersivo) para monopolar. Un contacto pobre con la piel concentra la corriente y puede quemar; por eso se comprueba antes de usar, como en el desafío de inspección.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:56,y:75,label:'Superficie adhesiva',note:'Debe adherirse por completo a la piel; un despegue parcial concentra la corriente en el área que sí hace contacto.'},{x:50,y:33,label:'Conector al generador',note:'Se conecta al generador antes de activar la monopolar; sin este circuito cerrado, no hay retorno seguro de la corriente.'}]},
    {file:'canula-metalica',title:'Cánula completamente metálica',kind:'FOTOGRAFÍA REAL',caption:'Cánula y trocar totalmente metálicos. Un eje sin secciones de plástico disipa la corriente capacitiva por su superficie; el riesgo descrito en el desafío de energía aparece con cánulas híbridas de metal y plástico, no con esta.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:15,y:52,label:'Punta',note:'El trocar puntiagudo entra primero; el eje que lo rodea es enteramente metálico.'},{x:70,y:32,label:'Cuerpo metálico continuo',note:'Sin secciones de plástico en el eje, la corriente capacitiva se disipa por toda la superficie metálica.'}]},
    {file:'funda-aislante',title:'Funda protectora',kind:'FOTOGRAFÍA REAL',caption:'Instrumento cubierto con una funda protectora mientras se manipula. Cubrir cables e instrumentos entre usos reduce el contacto accidental con superficies o piel.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:62,y:60,label:'Extremo cubierto',note:'La funda protege el extremo del instrumento mientras no está en uso activo.'}]}],
  5:[{file:'theatre',title:'Sala y sistemas',kind:'FOTOGRAFÍA REAL',caption:'Imagen, luz e insuflación son rutas distintas. En la misión deberás asociar cada alerta con una verificación dirigida.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg',points:[{x:34,y:53,label:'Torre audiovisual',note:'Las pantallas y equipos están agrupados en la torre. Ante una alerta, identifica primero qué sistema cambió.'}]},{file:'lap-tower',title:'Torre en contexto hospitalario',kind:'FOTOGRAFÍA REAL',caption:'Monitor y unidad de la torre visibles detrás del personal. Relaciona las alertas con el subsistema correcto, no con la marca del equipo.',credit:'Justin Ontiveros / U.S. Navy · dominio público',source:'https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Laparoscopy_donation_(8147071).jpg'},{file:'insuflador',title:'Insuflador de CO₂',kind:'FOTOGRAFÍA REAL',caption:'Panel del insuflador con presión y flujo programados (set) y reales (actual). Estos dos valores juntos indican si hay fuga u obstrucción, como en las alertas de este sector.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:28,y:57,label:'Presión (set / real)',note:'Presión programada arriba, presión real del abdomen abajo. Una presión real muy distinta de la programada es la primera pista de una alerta.'},{x:52,y:66,label:'Flujo (set / real)',note:'El flujo indica cuánto gas está saliendo. Presión baja con flujo alto sugiere fuga; presión alta con flujo en cero sugiere obstrucción.'}]},
    {file:'botella-co2',title:'Botella de CO₂',kind:'FOTOGRAFÍA REAL',caption:'Botella de CO₂ con su válvula. Si tras cambiarla no llega gas, lo primero es comprobar que la válvula esté abierta y bien conectada al insuflador.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:42,y:13,label:'Válvula',note:'Se comprueba que esté abierta y bien conectada antes de buscar otras causas de falta de gas.'}]},
    {file:'monitor-torre',title:'Monitor con imagen quirúrgica',kind:'FOTOGRAFÍA REAL',caption:'Referencia de una imagen laparoscópica nítida y bien iluminada, en un monitor real. Compárala mentalmente con lo descrito en cada señal de este sector: borrosa, oscura, con humo o con un cambio súbito de color.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:44,y:22,label:'Imagen de referencia',note:'Nítida, bien iluminada y sin humo: así se ve el campo cuando ningún sistema falla.'}]}],
  6:[{file:'needle-holder',title:'Portaagujas laparoscópico bloqueable',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'La fuente identifica el instrumento como portaagujas laparoscópico bloqueable. Observa el eje largo y el extremo de prensión antes de ordenar la preparación y conciliación.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_jehelec.jpg',points:[{x:13,y:48,label:'Mango bloqueable',note:'Verifica el mecanismo de agarre y bloqueo según el modelo solicitado.'},{x:91,y:47,label:'Extremo de prensión',note:'El extremo debe revisarse antes de cargar la aguja y entregarla.'}]},
    {file:'portaagujas-2',title:'Portaagujas laparoscópico',kind:'FOTOGRAFÍA REAL',caption:'Otro portaagujas real, con detalle de la mordaza estriada que sujeta la aguja sin dejarla girar.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:78,y:20,label:'Mordaza estriada',note:'La estría fija la aguja en el ángulo cargado; una mordaza gastada deja girar la aguja durante la sutura.'},{x:30,y:85,label:'Mango de anillas',note:'Controla la apertura y el bloqueo del portaagujas.'}]},
    {file:'sobre-sutura',title:'Cómo leer un sobre de sutura',kind:'DISEÑO PROPIO · NO FOTOGRAFÍA',caption:'Diagrama propio sobre un sobre de sutura real, con los datos que se confirman antes de cargar y entregar: material, calibre USP, código y descripción de la aguja. Es justo lo que pide el desafío «Antes de entregar la aguja».',credit:'GPA Academy · Diseño propio',source:'',points:[{x:44,y:28,label:'Calibre USP',note:'El calibre (por ejemplo 5-0) debe coincidir exactamente con lo solicitado.'},{x:28,y:60,label:'Código de la aguja',note:'Identifica el tipo exacto de aguja del fabricante.'},{x:52,y:78,label:'Descripción de la aguja',note:'La curvatura y el tamaño se representan aquí; se comparan con lo pedido antes de cargar.'}]}],
  7:[
    {file:'hernia-set',title:'Set laparoscópico real',kind:'FOTOGRAFÍA REAL',caption:'Esta mesa es una referencia general de instrumental para una operación laparoscópica de hernia; no representa el set completo de las especialidades simuladas. Resuelve por función y verifica compatibilidad.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg',points:[{x:15,y:34,label:'Acceso',note:'Aquí se agrupan instrumentos de acceso. El set avanzado concreto se confirma con la solicitud del equipo.'},{x:53,y:34,label:'Manipulación',note:'La mesa incluye pinzas largas de manipulación, pero no todos los dispositivos de las especialidades simuladas.'},{x:81,y:22,label:'Conexiones',note:'Los cables y tubos exigen una comprobación de compatibilidad antes de su uso.'}]},
    {file:'stapler-eea',title:'Grapadora circular EEA',kind:'FOTOGRAFÍA REAL',caption:'Referencia de una grapadora circular EEA. Comprueba el modelo, tamaño y compatibilidad solicitados para el caso real.',credit:'Rocco Cusari · dominio público',source:'https://commons.wikimedia.org/wiki/File:Stapler_EEA.jpg'},
    {file:'endobag-use',title:'Bolsa de extracción en uso',kind:'FOTOGRAFÍA CLÍNICA',caption:'Bolsa de extracción visible durante una apendicectomía laparoscópica. La foto muestra el concepto, no el modelo del set solicitado.',credit:'Parveen Bhatia et al. · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Endobag_Appendix_01.jpg'},
    {file:'cartuchos-grapadora',title:'Cartuchos de colores',kind:'FOTOGRAFÍA REAL',caption:'Cartuchos de grapadora lineal en distintos colores. Cada color corresponde a una altura de grapa distinta; el cartucho correcto se confirma con el cirujano, nunca se elige por costumbre.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:25,y:50,label:'Un color',note:'Cada color de cartucho corresponde a una altura de grapa específica del fabricante.'},{x:75,y:50,label:'Otro color',note:'Cartuchos de distinto color no son intercambiables entre sí sin confirmar la indicación.'}]},
    {file:'eea-detalle',title:'Grapadora circular EEA: componentes',kind:'FOTOGRAFÍA REAL',caption:'Detalle de una grapadora circular EEA con el yunque separado del cuerpo. Verificar que ambos componentes correspondan al mismo tamaño y referencia es parte de la preparación descrita en el desafío de anastomosis.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:10,y:68,label:'Yunque (anvil)',note:'Se acopla al cuerpo antes del disparo; su tamaño debe coincidir con el del cartucho.'},{x:24,y:78,label:'Acoplamiento del cartucho',note:'Aquí se confirma que el yunque y el cuerpo son de la misma referencia antes de continuar.'}]},
    {file:'bolsa-extraccion-2',title:'Bolsa de extracción (fuera de uso)',kind:'FOTOGRAFÍA REAL',caption:'La misma bolsa de extracción, aquí desplegada y fuera del cuerpo: se aprecia el aro, la red y el mango. Compárala con la fotografía clínica anterior, donde se ve en uso real.',credit:'GPA Academy · Fotografía propia',source:''}
    ],
  8:[
    {file:'theatre',title:'Quirófano de guardia',kind:'FOTOGRAFÍA REAL',caption:'Un caso encadenado recorre toda la sala: torre, mesa de instrumental, campo y conteo. La integridad se arrastra de una etapa a la siguiente.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg'},
    {file:'hernia-set',title:'Mesa preparada',kind:'FOTOGRAFÍA REAL',caption:'Referencia general de una mesa laparoscópica real. Cada etapa del caso pide algo distinto de ella.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg'},
    {file:'clipadora',title:'Clipadora laparoscópica',kind:'FOTOGRAFÍA REAL',caption:'Clipadora real, con detalle del extremo. En una colecistectomía se usa para ocluir el conducto y la arteria císticos antes de dividirlos; el equipo confirma el tamaño de clip antes de aplicarlo.',credit:'GPA Academy · Fotografía propia',source:'',points:[{x:16,y:38,label:'Extremo con clip',note:'Aquí se carga y aplica el clip sobre la estructura a ocluir.'},{x:80,y:68,label:'Mango de anillas',note:'Controla la apertura y el disparo del clip.'}]},
    {file:'clips-laparoscopicos',title:'Clips de distintos tamaños',kind:'FOTOGRAFÍA REAL',caption:'Cartuchos de clips de tamaños distintos, identificados por color. Igual que con los cartuchos de grapadora, el tamaño correcto se confirma con el equipo, nunca se elige por costumbre.',credit:'GPA Academy · Fotografía propia',source:''}
  ]
};

export const toolPhotos={
  optic:{file:'optic',note:'Óptica laparoscópica real'},
  mary:{file:'dissector',note:'Disector laparoscópico real; subtipo no especificado'},
  grasper:{file:'grasper',note:'Grasper laparoscópico dentado real'},
  holder:{file:'needle-holder',note:'Portaagujas laparoscópico bloqueable real'},
  needle:{file:'needle-holder',note:'Portaagujas laparoscópico bloqueable real'},
  trocar:{file:'trocar-product',note:'Trocares reales; verifica el modelo y calibre'},
  babcock:{file:'babcock-laparoscopic',note:'Babcock laparoscópica real de 5 mm; detalle distal'},
  gas:{file:'insuflador',note:'Insuflador de CO₂ real; verifica presión y flujo'},
  hook:{file:'monopolar-hook',note:'Gancho monopolar laparoscópico real'},
  tube:{file:'co2-tube.svg',note:'Esquema de tubo de CO₂; verifica la conexión'},
  nathanson:{file:'nathanson',note:'Retractor hepático Nathanson real'},
  stapler:{file:'linear-stapler',note:'Grapadora lineal laparoscópica real; verifica el modelo y la carga'},
  circular:{file:'stapler-eea',note:'Grapadora circular EEA real'},
  bag:{file:'endobag-use',note:'Bolsa de extracción real en uso clínico'},
  maryland:{file:'dissector',note:'Disector laparoscópico real; subtipo no especificado'}
};
