// Fotografías de Wikimedia Commons y de una publicación CC BY. Véase CREDITOS-IMAGENES.md.
export const visualAtlas={
  1:[
    {file:'theatre',title:'Quirófano laparoscópico',kind:'FOTOGRAFÍA REAL',caption:'Reconoce el entorno y localiza la torre con pantallas y equipos antes de trazar la cadena de imagen.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg',points:[{x:34,y:53,label:'Torre audiovisual',note:'La torre con pantallas se aprecia a la izquierda de la mesa. La ruta de imagen se resuelve por componentes, no por la posición física en la foto.'},{x:48,y:65,label:'Mesa de operaciones',note:'La mesa es un elemento del entorno, no un nodo de la cadena de vídeo.'}]},
    {file:'lap-tower',title:'Torre de laparoscopia',kind:'FOTOGRAFÍA REAL',caption:'Torre STORZ fotografiada durante una donación hospitalaria. El monitor y una unidad de equipo son visibles detrás de las personas; no se deben inferir conexiones desde esta imagen.',credit:'Justin Ontiveros / U.S. Navy · dominio público',source:'https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Laparoscopy_donation_(8147071).jpg'},
    {file:'instruments',title:'Instrumental laparoscópico',kind:'FOTOGRAFÍA REAL',caption:'Observa el eje largo y los mandos de instrumentos reales. Su forma no identifica por sí sola la ruta de señal.',credit:'ignis · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_Hand_Instruments_001_JPN.jpg'}
  ],
  2:[
    {file:'hernia-set',title:'Mesa de instrumental',kind:'FOTOGRAFÍA REAL',caption:'Un set real mezcla acceso, manipulación, cables y otros elementos. Inspecciona las zonas numeradas y confirma el modelo solicitado.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg',points:[{x:15,y:34,label:'Instrumentos de acceso',note:'La zona izquierda contiene instrumentos de acceso. En un caso real se confirman tipo y calibre antes de seleccionarlos.'},{x:53,y:34,label:'Pinzas largas',note:'En el centro hay instrumentos largos de manipulación. La foto no basta para identificar cada modelo específico.'},{x:81,y:22,label:'Cable y conexión',note:'Los cables se inspeccionan y se relacionan con el equipo compatible; no se eligen por apariencia solamente.'}]},
    {file:'dissector',title:'Disector laparoscópico',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Mango, eje largo y mordazas de un disector laparoscópico. La fuente no especifica el subtipo Maryland, por lo que el juego no le atribuye ese nombre.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_disektor.jpg'},
    {file:'grasper',title:'Grasper laparoscópico dentado',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Mango, eje largo y mordazas dentadas de un grasper laparoscópico. Es una pinza laparoscópica de tracción firme, no una Babcock.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_grasp.jpg'},
    {file:'trocar-product',title:'Familia de trocares',kind:'FOTOGRAFÍA REAL',caption:'Fotografía de trocares desechables. El modelo y calibre se confirman en el material solicitado; la foto no identifica el producto del desafío.',credit:'Magnus1313 · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Trocar_family.jpg'},
    {file:'babcock-laparoscopic',title:'Babcock laparoscópica de 5 mm',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Detalle distal aislado de una Babcock laparoscópica reutilizable de 5 mm, con mordazas redondeadas y fenestradas para prensión atraumática.',credit:'Bezerra et al. · Figura 1A recortada · CC BY 4.0',source:'https://periodicos.newsciencepubl.com/arace/article/view/8981'}
  ],
  3:[
    {file:'access',title:'Acceso con puerto real',kind:'FOTOGRAFÍA CLÍNICA',caption:'Imagen clínica de un acceso transumbilical. El esquema del desafío simplifica la triangulación; no prescribe sitios de inserción.',credit:'G Srikanth et al. · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopy_01.jpg',points:[{x:59,y:46,label:'Puerto de acceso',note:'Aquí se ve el puerto de acceso. La foto documenta un procedimiento específico; no define por sí sola la geometría de otros casos.'}]},
    {file:'position',title:'Posición de Trendelenburg',kind:'FOTOGRAFÍA CON MANIQUÍ',caption:'La fotografía ilustra la inclinación cefálica inferior. La posición real depende del procedimiento y del equipo.',credit:'G. Rees Doyle y J. A. McCutcheon · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Trendelenburg_position.jpg',points:[{x:13,y:43,label:'Extremo cefálico',note:'La cabeza del maniquí queda más baja que los pies en esta demostración de Trendelenburg.'},{x:88,y:29,label:'Extremo podálico',note:'El extremo de los pies queda elevado. El equipo establece la posición y protege al paciente según el procedimiento.'}]},
    {file:'trocar',title:'Esquema de puertos',kind:'ESQUEMA · NO FOTOGRAFÍA',caption:'Distribución ilustrativa de accesos. No usar como plantilla de colocación clínica.',credit:'Huatulco · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Trocar_in_VLC.JPG'}
  ],
  4:[{file:'dissector',title:'Disector laparoscópico bajo inspección',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'Examina mango, eje y extremo de este disector laparoscópico. Los fallos descritos en la misión son un escenario simulado, no defectos visibles en esta foto.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_disektor.jpg',points:[{x:21,y:51,label:'Mango',note:'Comprueba integridad y mecanismo del mango según la lista de verificación local.'},{x:58,y:23,label:'Eje laparoscópico',note:'Inspecciona el eje y su aislamiento cuando el dispositivo utiliza energía. La foto no representa un daño real.'},{x:90,y:34,label:'Extremo de trabajo',note:'Confirma la integridad del extremo y la compatibilidad antes del uso.'}]}],
  5:[{file:'theatre',title:'Sala y sistemas',kind:'FOTOGRAFÍA REAL',caption:'Imagen, luz e insuflación son rutas distintas. En la misión deberás asociar cada alerta con una verificación dirigida.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg',points:[{x:34,y:53,label:'Torre audiovisual',note:'Las pantallas y equipos están agrupados en la torre. Ante una alerta, identifica primero qué sistema cambió.'}]},{file:'lap-tower',title:'Torre en contexto hospitalario',kind:'FOTOGRAFÍA REAL',caption:'Monitor y unidad de la torre visibles detrás del personal. Relaciona las alertas con el subsistema correcto, no con la marca del equipo.',credit:'Justin Ontiveros / U.S. Navy · dominio público',source:'https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Laparoscopy_donation_(8147071).jpg'}],
  6:[{file:'needle-holder',title:'Portaagujas laparoscópico bloqueable',kind:'FOTOGRAFÍA REAL · IDENTIDAD VERIFICADA',caption:'La fuente identifica el instrumento como portaagujas laparoscópico bloqueable. Observa el eje largo y el extremo de prensión antes de ordenar la preparación y conciliación.',credit:'David.Mirth · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Laparo_jehelec.jpg',points:[{x:13,y:48,label:'Mango bloqueable',note:'Verifica el mecanismo de agarre y bloqueo según el modelo solicitado.'},{x:91,y:47,label:'Extremo de prensión',note:'El extremo debe revisarse antes de cargar la aguja y entregarla.'}]}],
  7:[
    {file:'hernia-set',title:'Set laparoscópico real',kind:'FOTOGRAFÍA REAL',caption:'Esta mesa es una referencia general de instrumental para una operación laparoscópica de hernia; no representa el set completo de las especialidades simuladas. Resuelve por función y verifica compatibilidad.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg',points:[{x:15,y:34,label:'Acceso',note:'Aquí se agrupan instrumentos de acceso. El set avanzado concreto se confirma con la solicitud del equipo.'},{x:53,y:34,label:'Manipulación',note:'La mesa incluye pinzas largas de manipulación, pero no todos los dispositivos de las especialidades simuladas.'},{x:81,y:22,label:'Conexiones',note:'Los cables y tubos exigen una comprobación de compatibilidad antes de su uso.'}]},
    {file:'stapler-eea',title:'Grapadora circular EEA',kind:'FOTOGRAFÍA REAL',caption:'Referencia de una grapadora circular EEA. Comprueba el modelo, tamaño y compatibilidad solicitados para el caso real.',credit:'Rocco Cusari · dominio público',source:'https://commons.wikimedia.org/wiki/File:Stapler_EEA.jpg'},
    {file:'endobag-use',title:'Bolsa de extracción en uso',kind:'FOTOGRAFÍA CLÍNICA',caption:'Bolsa de extracción visible durante una apendicectomía laparoscópica. La foto muestra el concepto, no el modelo del set solicitado.',credit:'Parveen Bhatia et al. · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Endobag_Appendix_01.jpg'}
    ],
  8:[
    {file:'theatre',title:'Quirófano de guardia',kind:'FOTOGRAFÍA REAL',caption:'Un caso encadenado recorre toda la sala: torre, mesa de instrumental, campo y conteo. La integridad se arrastra de una etapa a la siguiente.',credit:'Dr.jayesh amin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Laparoscopic_operating_theatre.jpg'},
    {file:'hernia-set',title:'Mesa preparada',kind:'FOTOGRAFÍA REAL',caption:'Referencia general de una mesa laparoscópica real. Cada etapa del caso pide algo distinto de ella.',credit:'Anpol42 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Instruments_for_laparoscopic_Hernia_Operation.jpg'}
  ]
};

export const toolPhotos={
  optic:{file:'optic',note:'Óptica laparoscópica real'},
  mary:{file:'dissector',note:'Disector laparoscópico real; subtipo no especificado'},
  grasper:{file:'grasper',note:'Grasper laparoscópico dentado real'},
  holder:{file:'needle-holder',note:'Portaagujas laparoscópico bloqueable real'},
  needle:{file:'needle-holder',note:'Portaagujas laparoscópico bloqueable real'},
  trocar:{file:'trocar-product',note:'Trocares reales; verifica el modelo y calibre'},
  babcock:{file:'babcock-laparoscopic',note:'Babcock laparoscópica real de 5 mm; detalle distal'},
  gas:{file:'insufflator.svg',note:'Esquema de insuflador; verifica el equipo'},
  hook:{file:'monopolar-hook.svg',note:'Esquema de gancho monopolar; verifica el modelo'},
  tube:{file:'co2-tube.svg',note:'Esquema de tubo de CO₂; verifica la conexión'},
  nathanson:{file:'nathanson.svg',note:'Esquema de retractor Nathanson'},
  stapler:{file:'linear-stapler.svg',note:'Esquema de grapadora lineal; no identifica un modelo Endo-GIA'},
  circular:{file:'stapler-eea',note:'Grapadora circular EEA real'},
  bag:{file:'endobag-use',note:'Bolsa de extracción real en uso clínico'},
  maryland:{file:'dissector',note:'Disector laparoscópico real; subtipo no especificado'}
};
